{{- include "chart.validateDbConfig" . -}}
{{- $dbTls := .Values.db.tls | default dict -}}
{{- $dbTlsCaCert := $dbTls.caCert | default "" -}}
{{- $dbTlsMode := $dbTls.mode | default "none" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}dbmigrator-config
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  tern.conf: |-
    [database]
    host = {{ default (printf "%s-postgresql.%s" .Release.Name .Release.Namespace) .Values.db.host }}
    port = {{ .Values.db.port }}
    database = {{ .Values.db.dbname }}
    user = {{ .Values.db.user }}
    password = {{ .Values.db.password }}
{{- if ne $dbTlsMode "none" }}
    sslmode = {{ $dbTlsMode }}
{{- else }}
    sslmode = {{ .Values.db.sslMode | lower }}
{{- end }}
{{- if $dbTlsCaCert }}
    sslrootcert = {{ .Values.configDir }}/ca.crt
  ca.crt: |-
{{- $dbTlsCaCert | nindent 4 }}
{{- end }}
