apiVersion: v2
name: ocg
description: Open Community Groups
type: application
version: 0.1.1-1
appVersion: 0.1.0
kubeVersion: ">= 1.19.0-0"
keywords:
  - cncf
  - community
  - groups
maintainers:
  - name: Sergio
    email: tegioz@icloud.com
  - name: Cintia
    email: cynthiasg@icloud.com
dependencies:
  - name: postgresql
    version: 18.0.15
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
