# Build tern
FROM golang:1.24-alpine3.22 AS tern
RUN apk --no-cache add git
RUN go install github.com/jackc/tern/v2@latest

# Build final image
FROM alpine:3.22.1
RUN apk --no-cache add git perl-app-cpanminus postgresql16-client
RUN cpanm --no-wget TAP::Parser::SourceHandler::pgTAP
RUN addgroup -S db-tests && adduser -S db-tests -G db-tests
COPY --from=tern /go/bin/tern /usr/local/bin
